function lib = parse_liberty(filepath)
%PARSE_LIBERTY Minimal Liberty (.lib) parser for this project's 7-cell
%   180nm library (INV, NAND2, NOR2, AND2, OR2, XOR2, DFF).
%
%   NOT a general-purpose Liberty parser -- it extracts exactly the fields
%   this power model needs (corner voltage/temperature, cell area, cell
%   leakage power, input-pin capacitance, cell_rise delay) from the real
%   characterized files in data/liberty/, generated by
%   03_cmos_cell_library/char/characterize.py. Every numeric value
%   returned is read directly out of the .lib text -- nothing here is
%   hand-entered.
%
%   lib = PARSE_LIBERTY('../data/liberty/cells_180nm_TT.lib')
%   lib.nom_voltage, lib.nom_temperature   -- corner conditions
%   lib.cells.INV.area / .leakage_nW / .cap_pF / .delay_ps  (and NAND2, ...)

    txt = fileread(filepath);

    lib = struct();
    v_tok = regexp(txt, 'nom_voltage\s*:\s*([\d.]+)', 'tokens', 'once');
    t_tok = regexp(txt, 'nom_temperature:\s*(-?[\d.]+)', 'tokens', 'once');
    lib.nom_voltage     = str2double(v_tok{1});
    lib.nom_temperature = str2double(t_tok{1});
    lib.cells = struct();

    cell_names = {'INV', 'NAND2', 'NOR2', 'AND2', 'OR2', 'XOR2', 'DFF'};
    for i = 1:numel(cell_names)
        name  = cell_names{i};
        block = local_extract_cell_block(txt, name);
        if isempty(block)
            continue
        end
        c.area       = local_grab_scalar(block, 'area');
        c.leakage_nW = local_grab_scalar(block, 'cell_leakage_power');

        caps = regexp(block, 'capacitance\s*:\s*([\d.]+)', 'tokens');
        c.cap_pF = mean(cellfun(@(t) str2double(t{1}), caps));

        rises = regexp(block, 'cell_rise\s*:\s*([\d.]+)', 'tokens');
        c.delay_ps = str2double(rises{1}{1});

        lib.cells.(name) = c;
    end
end

function v = local_grab_scalar(block, key)
    tok = regexp(block, [key '\s*:\s*([\d.]+)'], 'tokens', 'once');
    v = str2double(tok{1});
end

function block = local_extract_cell_block(txt, name)
%LOCAL_EXTRACT_CELL_BLOCK Return the full "cell (NAME) { ... }" substring,
%   matching braces by depth-counting (cell blocks contain nested pin{}/
%   timing{} blocks, so a naive non-greedy regex would stop too early).
    pat = ['cell \(' name '\)\s*\{'];
    start_idx = regexp(txt, pat, 'start', 'once');
    block = '';
    if isempty(start_idx)
        return
    end
    depth = 0;
    n = length(txt);
    i = start_idx;
    while i <= n
        ch = txt(i);
        if ch == '{'
            depth = depth + 1;
        elseif ch == '}'
            depth = depth - 1;
            if depth == 0
                block = txt(start_idx:i);
                return
            end
        end
        i = i + 1;
    end
end
